Scaffolding
fullstacktf/order-food-backend pull request #2
Opened 2021-11-13 01:17 UTC by dtote

Fix #1

2021-11-13 21:34 UTC, ManuYuzu requested changes
Revisión de cohesión:
El modelo _Client_ contiene un []interface de 'address' mientras que el modelo _Restaurant_ contiene un struct

2021-11-13 21:36 UTC, ManuYuzu reviewed
**Importante**
La versión de GO en los módulos es la 1.17 mientras que el Dockerfile está trabajando con la 1.16

2021-11-13 21:36 UTC, ManuYuzu approved these changes

2021-11-13 21:39 UTC, ManuYuzu reviewed
Llamar a las funcionalidades de modificación con un 'Put-', si bien es correcto, sintácticamente creo que sería más legible si las nombramos como 'Update-' o 'Modify-'

2021-11-14 20:47 UTC, jncabdom approved these changes
Estuve un rato mirando a ver si te cogía un fallo o algo man pero na

De locos

2021-11-14 21:14 UTC, jncabdom commented on src/models/restaurant.go
> +	Username string           `json:"username"`
El username realmente sobra. En todo caso sería para el login, y para eso ya tenemos el mail
```suggestion
```

2021-11-14 21:19 UTC, paolaski commented on src/models/restaurant.go
> +	Username string           `json:"username"`
De acuerdo según el modelo de datos que hicimos, ok con Nico.

2021-11-14 22:29 UTC, dtote commented on src/models/restaurant.go
> +	Username string           `json:"username"`
Perfecto, lo quito, es preferible manejar el login y el registro mediante otros datos

2021-11-14 22:55 UTC, jncabdom approved these changes

2021-11-14 23:26 UTC, ManuYuzu approved these changes

2021-11-14 23:27 UTC, ManuYuzu approved these changes

2021-11-14 23:45 UTC, merged