CI (testing) y CD al server de DigitalOcean
fullstacktf/order-food-backend pull request #49
Opened 2021-12-03 20:14 UTC by jncabdom

Fix #47 #48

2021-12-03 20:16 UTC, jncabdom commented
Checkense eso, faltaría cambiar el directorio de destino porque ahora mismo están las cosas en comiditapp-pruebas pero vamos eso es un cambio chorra.

Cuando se hace un push o una PR, se testea el código. Si es un push y es en main, aparte se construye una imagen nueva de Docker, se mete al servidor, la pilla y reinicia el server.

2021-12-04 19:49 UTC, dtote requested changes

2021-12-04 19:49 UTC, dtote commented on .dockerignore
> +
```suggestion
No sé si en este fichero querias meter algo, pero si no lo vas a hacer bórralo 
```

2021-12-04 21:53 UTC, jncabdom commented on .dockerignore
> +
A ver creo que es buena práctica tenerlo y quizá meterle el .idea el .vscode etc. 

Como nos copiamos el src directamente nunca se deberían tocar, pero a lo mejor renta tenerlos por buenas prácticas?

2021-12-07 09:13 UTC, dtote approved these changes

2021-12-07 17:01 UTC, ManuYuzu approved these changes

2021-12-07 17:03 UTC, dtote approved these changes

2021-12-07 17:49 UTC, merged